### ISSUE TITLE
Fix encoding error on blacklight crawler

### ISSUE THREAD

**Issue by andkamau** [CodeForAfrica/aleph#5]
To reproduce, run: `aleph crawl blacklight` using [http://demo.projectblacklight.org/](http://demo.projectblacklight.org/) as the source

> INFO:aleph.crawlers.blacklight:Scraped doc 2008055818
> ERROR:aleph.crawlers.crawler:'ascii' codec can't encode character u'\u0300' in position 2138: ordinal not in range(128)
> Traceback (most recent call last):
>   File "/Users/aventador/code/c4a/aleph/aleph/crawlers/crawler.py", line 24, in execute
>     self.crawl(**kwargs)
>   File "/Users/aventador/code/c4a/aleph/aleph/crawlers/blacklight.py", line 104, in crawl
>     self.crawl_page(base_url, page_number)
>   File "/Users/aventador/code/c4a/aleph/aleph/crawlers/blacklight.py", line 73, in crawl_page
>     response = self.crawl_document(base_url, i['id'])
>   File "/Users/aventador/code/c4a/aleph/aleph/crawlers/blacklight.py", line 58, in crawl_document
>     self.emit_content(self.source, meta, content)
>   File "/Users/aventador/code/c4a/aleph/aleph/crawlers/crawler.py", line 64, in emit_content
>     fh.write(content)
> UnicodeEncodeError: 'ascii' codec can't encode character u'\u0300' in position 2138: ordinal not in range(128)
>

**Comment by andkamau** [comment]
https://github.com/CodeForAfrica/aleph/commit/91d73b494b802fb3ab3541e52de9170f4bb99806
